### ISSUE TITLE
rpc-websockets client fails to resolve localhost

### ISSUE THREAD

**Issue by Rawa** [qaap/rpc-websockets#14]
Just spent several hours debugging rpc-websockets and eventually uWebsockets because my rpc-websocket client couldn't connect to localhost.

Eventually found the issue, if localhost is resolved as ::1 (localhost of ipv6) The underlying library uWebsockets will produce the following error:
```
{ message: 'uWs client connection error',
  stack: 'uWs client connection error' }
```

For now I suggest we link this issue to the bug [existing issue ](https://github.com/uNetworking/uWebSockets/issues/342)in uWebsocket so other people can be aware of this issue.

**Comment by Rawa** [comment]
https://github.com/uNetworking/uWebSockets/issues/342

**Comment by mkozjak** [comment]
@Rawa: Should work in 4.0.0, since I've switched back to `ws`.
