### ISSUE TITLE
Client 'on' params as an Object

### ISSUE THREAD

**Issue by msergdeez** [qaap/rpc-websockets#19]
https://github.com/qaap/rpc-websockets/blob/c335c872f8ea46df06848d21ac57df30457322d7/src/lib/client.js#L218

I can't use notification parameters if it is an Object, only if it is an Array.

**Comment by mkozjak** [comment]
Would be handy if you attached an example and an error, so I don't have to lose time on reverse engineering.

**Comment by msergdeez** [comment]
I subscribe my Client to 'act.change' event:

`ws.on('act.change', p => {console.log(p)})`

and on 
```json 
{"jsonrpc":"2.0","notification":"act.change","params":{"id":"59ad722f7520c26f1249fe29"}}
```
notification I see 'undefined' in the console due to "params" is an Object and params.length === undefined, 

https://github.com/qaap/rpc-websockets/blob/c335c872f8ea46df06848d21ac57df30457322d7/src/lib/client.js#L225
```
for (let i = 0; i < message.params.length; i++) {
 // ... will never happen
}

```

**Comment by msergdeez** [comment]
I made a custom json.Marshal for encoding any notification params as an array on the server-side but it's sad.

**Comment by mkozjak** [comment]
Thanks!!! Will take a look into it asap!

**Comment by msergdeez** [comment]
Awesome! Thanks for the response!

**Comment by mkozjak** [comment]
@msergdeez: 3.5.0 including the fix is now published!
