### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by PhilAndrew** [qaap/rpc-websockets#20]
I paste the example as you have it on your README.md and run it and the only output is
[ 'feedUpdated' ]

**Comment by dstreet** [comment]
I think that is expected because the only thing that is logged is the event list on the server.

**Comment by PhilAndrew** [comment]
I put log in ws.on('open', function() { and it never happens :(

**Comment by dstreet** [comment]
ok. I'm not able to test on Windows, but if you provide a full code example I'll see if it is a universal bug

**Comment by mkozjak** [comment]
Closing as inactive.
