### ISSUE TITLE
Need help: How work with this API, Add ID to JSON-RPC call

### ISSUE THREAD

**Issue by meotimdihia** [qaap/rpc-websockets#21]
https://hitbtc.com/api#get-currencies  
How to add id to JSON-RPC call  
```json
{
  "method": "getCurrency",
  "params": {
    "currency": "ETH"
  },
  "id": 123
}
```

**Comment by mkozjak** [comment]
Currently ID cannot be set manually. Why would you need this? ID is set automatically and should not make any differences for you at all..

**Comment by meotimdihia** [comment]
Sorry, it is work now, but response time is very slow. 

```javascript

ws.on('open', function() {
  // call an RPC method with parameters

    ws.call('getCurrency', {currency: 'ETH'}).then(function(result) {
      console.log(result)
    })

    ws.call('login',{
        "algo": "BASIC",
        "pKey": key,
        "sKey": secret
      }
    ).then(function(result) {
        console.log(result);
        ws.call('getTradingBalance').then(function(result) {
        console.log(result);
      }
  });
})
```

Its faster if i use `ws` package .

**Comment by mkozjak** [comment]
I highly doubt it it's slower than `ws`, because I'm using `uws` instead, which is a lot faster. Can you provide any tests and times?

**Comment by meotimdihia** [comment]
If you run this code, it take more 10s to response

`index.js`
``` javascript
const rpc = require('rpc-websockets').Client

const baseUrl = 'wss://api.hitbtc.com/api/2/ws';

var ws = new rpc(baseUrl)

ws.on('open', function() {
  // call an RPC method with parameters
  ws.call('getCurrency', {currency: 'ETH'}).then(function(result) {
    console.log(2);
    console.log(result)
  })
})
```


`index2.js` under 5s 
```
const WebSocket = require('ws');

const baseUrl = 'wss://api.hitbtc.com/api/2/ws';

var ws = new WebSocket(baseUrl)
ws.on('open', function() {
    console.log('open');
    ws.send(JSON.stringify({
      "method": "getCurrency",
      "params": {
        "currency": "ETH"
      },
      "id": 123
    }));
})
```

and its strange, if i combile code in 2 files, then code use `rpc-websockets` will response immeditely.

**Comment by mkozjak** [comment]
On a Mac Mini 1 is `0.13s user 0.03s system 50% cpu 0.307 total` and 2 is `0.11s user 0.03s system 46% cpu 0.289 total`.

rpc-websockets does some computation with ws data, hence the overhead. But this is nowhere 5 or 10 seconds.

**Comment by meotimdihia** [comment]
I found out the problem: 
Reason is node version. I removed node 8.9 on my Windows Creators then reinstall node 6.x.
