### ISSUE TITLE
Request headers

### ISSUE THREAD

**Issue by psn80** [qaap/rpc-websockets#23]
I want to do authentication by token in the headers of requests
How to take request headers?

**Comment by mkozjak** [comment]
@psn80: Thanks for reporting. Waiting for upstream to solve the issue.

**Comment by mkozjak** [comment]
There's a need to patch the upstream uWebSockets library. It currently doesn't handle custom headers. This will take time to solve.

**Comment by dstreet** [comment]
Any update on this?

**Comment by mkozjak** [comment]
Unfortunately, no, as I try juggling between several different projects, at the moment.
As usual, PRs are welcome. There's a repo which should be patched here: https://github.com/qaap/uws-bindings

I could also use your fork if a patch is done, if you get it done before me. Sorry for the inconvenience.

**Comment by dstreet** [comment]
No worries. I completely understand. I'll try to take a look at this over the next few days

**Comment by mkozjak** [comment]
I've decided to switch back to `ws` to get features you guys need. I also decided not to lose time on uws which lacks certain features and is led by a person I do not approve actions of.
