### ISSUE TITLE
Browser client

### ISSUE THREAD

**Issue by dinkoivanov** [qaap/rpc-websockets#27]
Hi,

Thanks for the great library!
I've written a small Node JS server, and I want to use it from my frontend running in the browser. Can I do that?
I saw a dist/index.browser-bundle.js file and included it in my index.html. How can I instantiate the client using this bundle? Normally I would do:
`
var WebSocket = require('rpc-websockets').Client
`
`
var ws = new WebSocket('ws://localhost:8080')
`
What's the equivalent if using the browser-bundle?

Thanks!

Dinko

**Comment by mkozjak** [comment]
Hi and thanks for using this library! Please check this example https://gist.github.com/mkozjak/fa9296484c40445af516e563c65536bf
This should work for you!

**Comment by dinkoivanov** [comment]
Thanks for the quick reply Mario!

Where can I find the referenced **./lib/rpcwebsockets.js** file?

Regards,
Dinko

**Comment by mkozjak** [comment]
Depends on how you install dependencies with your bundler.
In example, when using browserify or webpack, you can just `require('rpc-websockets')` after install with `npm install rpc-websockets`.

**Comment by dinkoivanov** [comment]
Thanks Mario! I figured it out in the end.

**Comment by mkozjak** [comment]
Thanks! Feel free to write a simple example here if your setup is specific, maybe it will help someone else, also!

**Comment by AneliqBlagoeva** [comment]
Hello! I have the same issue as @dinkoivanov. I used the provided html example after installing rpc websockets but receive the error for not finding ./lib/rpcwebsockets.js. Could you please help me or navigate me to the file? 
P.S I successfully run server and client examples using the console.

**Comment by mkozjak** [comment]
Hi, @AneliqBlagoeva, it really depends on your bundler. In example, when using browserify or webpack, you can just require('rpc-websockets') after install with npm install rpc-websockets.
