### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by mkozjak** [qaap/rpc-websockets#9]
We need client support for internet browsers.
Should we rely on an html5 websocket implementation and do a separate browser logic?

**Comment by mkozjak** [comment]
Browser tests should also be included.

#zuul
#saucelabs

**Comment by soulhunter1987** [comment]
What about this issue? Generally current Client logic is fully appropriate for browser usage. The only main problem, as i see, is uws usage, which must be replaced with native WebSockets for browser.

**Comment by mkozjak** [comment]
Hi, @soulhunter1987!

For the browser we use browserify, which will take care of our client code.
After installing rpc-websockets, you can copy file ./dist/index.browser.js to your frontend code, since browserify bundled the entire library there for you.
An RPCWebSocket class is exposed there for you to use.

This is an example html: https://gist.github.com/mkozjak/fa9296484c40445af516e563c65536bf

Cheers!

**Comment by soulhunter1987** [comment]
That will do the job but, not very efficiently. It would be good to also allow compiling from source with webpack or some other bundling tools. That would allow to write ES6-style code and then bundle (and may be transpile for old browsers) it as appropriate for the project. Also it would reduce size of resulting bundle, because repeating dependencies would be included only once.

**Comment by soulhunter1987** [comment]
Automatic updates via npm/yarn are also not available with this approach, because one will need to copy new file to his project's public directory (of course that may be automated, but that's extra work).

**Comment by soulhunter1987** [comment]
index.browser.js is really HUGE now, because it includes uws (which is not needed there at all), eventemitter and many other libraries, which may already be used in the project.

**Comment by mkozjak** [comment]
Agreed. TBH, I'm not really experienced with bundlers, so could you point me in the right direction with some examples, maybe? Also, PR welcome!

**Comment by soulhunter1987** [comment]
First of all you need to supply "src" directory in the package along with "dist".
Then one approach is to manually import and pass "transport" object (uws or browser websocket) to Client constructor via dependency injection.
NodeJs usage would look like this then:
```javascript
import WebSocket from 'uws'
import {Client} from 'rpc-websocket';

connection = new Client(address, options, WebSocket)
connection.call(...)
```
And browser ES6 code would be:
```javascript
import {Client, WebSocketWrapper} from 'rpc-websocket';

connection = new Client(address, options, WebSocketWrapper)
connection.call(...)
```
where "WebSocketWrapper" is your src/lib/client/websocket.browser.js wrapper class.

So with this approach you give users a choice which transport to use. And it would allow usage of any other transport which implements compatible interface.

**Comment by soulhunter1987** [comment]
If you create a separate branch with this solution implemented - I could try and test it's browser usage.

**Comment by mkozjak** [comment]
@soulhunter1987: Can you please give me an example library/project where both src and dist are shipped and dependencies are handled like described?

**Comment by dstreet** [comment]
@mkozjak mongoose handles this situation pretty well without needing to publish the dist. I might be able to put together a PR sometime today.

**Comment by mkozjak** [comment]
@dstreet: I believe you meant 'src', since the dist directory should definitely be published. :)

**Comment by dstreet** [comment]
@mkozjak I got slammed with some other project work. I'm not sure when I'll have time to get to this, sorry.

**Comment by dstreet** [comment]
Finally got some time to work on this. I'll submit a PR soon.

**Comment by dstreet** [comment]
Submitted PR #13. @soulhunter1987 can you test this on your end?

**Comment by mkozjak** [comment]
Awesome work, @dstreet! Thanks!
Will wait for @soulhunter1987 to check up on it just in case and publish the update afterwards.

**Comment by dstreet** [comment]
Great, thanks!

**Comment by dstreet** [comment]
@soulhunter1987 Do you think you'll have time to review this soon? Turns out I need this for a project I'm working on.

**Comment by mkozjak** [comment]
@dstreet I will publish this release now. If it works for you, I am okay with it.

**Comment by dstreet** [comment]
@mkozjak Looks like you forgot to rebuild the `dist` before publishing to npm. I apologize if this was a miscommunication on my part

**Comment by mkozjak** [comment]
@dstreet I forgot to include the dist directory altogether. It was still in .gitignore.

**Comment by mkozjak** [comment]
@dstreet Published. Can you check on it, please?

**Comment by dstreet** [comment]
Still broken, but I found where the problem is. commit 2c20dddd5b87347189fc7e3e02084285b9aea00b reverted the change I had made to the build script
